name: QIP Author Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'contents/QIP/**'

jobs:
  validate-author:
    name: Validate QIP Author
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - name: Validate author can modify QIP
        run: |
          BASE_SHA=${{ github.event.pull_request.base.sha }}
          HEAD_SHA=${{ github.sha }}
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          
          echo "PR Author: $PR_AUTHOR"
          echo "Checking modified QIP files..."
          
          # Get modified QIP files (not newly added ones)
          MODIFIED_QIPS=$(git diff --name-only $BASE_SHA $HEAD_SHA -- contents/QIP/ | xargs -I {} sh -c 'git show $BASE_SHA:{} >/dev/null 2>&1 && echo {}' || true)
          
          if [ -z "$MODIFIED_QIPS" ]; then
            echo "No existing QIP files were modified. Validation passed."
            exit 0
          fi
          
          bun scripts/validate-author.ts "$PR_AUTHOR" $MODIFIED_QIPS 